accounts/urls.py
from django.urls import path, re_path, include
from .views import login_view, register_view, logout_view, CustomPasswordResetView, CustomPasswordResetConfirmView

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('django.contrib.auth.urls')),
]

car_rental_app/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from system.views import admin_car_list, admin_msg, order_list, car_created, order_update, order_delete, msg_delete
from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', admin_car_list, name='adminIndex'),
    path('listOrder/', order_list, name = "order_list"),
    re_path(r'^(?P<id>\d+)/editOrder/$', order_update, name = "order_edit"),
    re_path(r'^(?P<id>\d+)/deleteOrder/$', order_delete, name = "order_delete"),
    path('create/', car_created, name = "car_create"),
    path('message/', admin_msg, name='message'),
    re_path(r'^(?P<id>\d+)/deletemsg/$', msg_delete, name = "msg_delete"),
    path('car/', include('system.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system/urls.py
from django.urls import re_path
from django.contrib import admin
from . import views   

urlpatterns = [
    re_path(r'^$', views.home, name="home"),

    re_path(r'^carlist/$', views.car_list, name="car_list"),
    re_path(r'^createOrder/$', views.order_created, name="order_create"),

    re_path(r'^(?P<id>\d+)/edit/$', views.car_update, name="car_edit"),

    re_path(r'^(?P<id>\d+)/$', views.car_detail, name="car_detail"),
    re_path(r'^detail/(?P<id>\d+)/$', views.order_detail, name="order_detail"),

    re_path(r'^(?P<id>\d+)/delete/$', views.car_delete, name="car_delete"),
    re_path(r'^(?P<id>\d+)/deleteOrder/$', views.order_delete, name="order_delete"),

    re_path(r'^contact/$', views.contact, name="contact"),
    re_path(r'^newcar/$', views.newcar, name="newcar"),
    re_path(r'^(?P<id>\d+)/like/$', views.like_update, name="like"),
    re_path(r'^popularcar/$', views.popular_car, name="popularcar"),
]

templates/admin_index.html
{% extends 'base.html' %}
{% block title %}  Admin Site {% endblock %}

{% block delete_confirm %}
        <script type="text/javascript">
            function getConfirmation(){
               return confirm("Do you want to Delete ?");
            }
      </script>
    {% endblock %}
{% block search %}
{% endblock %}
{% block nav %}

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'adminIndex' %}"><span class="glyphicon glyphicon-home"></span> Car List</a></li>
        <li><a href="{% url 'order_list' %}"><span class="glyphicon glyphicon-tags"></span> Order List</a></li>
        <li><a href="{% url 'message' %}"><span class="glyphicon glyphicon-envelope"></span> Message</a></li>
          <li><a href="{% url 'car_create' %}"><span class="glyphicon glyphicon-plus"></span> Add Car</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-share"></span> Logout</a></li>
      </ul>
    </div>

{% endblock %}
{% block body %}
<div class='container table-responsive'>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading"><h5><strong><span class="glyphicon glyphicon-list"></span> All Car List</strong></h5> </div>
    <div class="panel-body">
  <strong class="navbar-form navbar-left" style="color: #5f5f5f;"><span class="glyphicon glyphicon-cog"></span> 25 Car Display Per Page </strong>

   <!-- search box-->

      <form method="GET" class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Car Search" value="{{request.GET.q}}" name="q">
        </div>
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Search</button>
      </form>

  <!-- Table -->

  <table class="table table-bordered table-striped table-hover">

   <tr>
    <th scope="col">Car Name</th>
  <th scope="col">Company Name</th>
  <th scope="col">Seat No</th>
  <th scope="col">Cost Par Day</th>
  <th scope="col">Like</th>
  <th scope="col">Actions</th>
  </tr>

      <tbody>
      {% for ob in car %}

    <tr>
    <td>{{ob.car_name}}</td>
    <td>{{ob.company_name}}</td>
    <td>{{ob.num_of_seats}}</td>
    <td>{{ob.cost_par_day}}</td>
    <td>{{ob.like}}</td>

    <td>

         <a href="{% url 'car_detail' ob.id %}"><button type="button" class="btn btn-info"><span class="glyphicon glyphicon-eye-open"></span></button></a>
         <a href="{% url 'car_edit' ob.id %}"><button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></button></a>
         <a href="{% url 'car_delete' ob.id %}"><button type="button" class="btn btn-danger" onclick="return getConfirmation()"><span class="glyphicon glyphicon-trash"></span></button></a>

    </td>
    </tr>
    {% endfor %}
</tbody>
  </table>

<nav>
  <ul class="pager">
    <li class="previous">{% if car.has_previous %}
            <a href="?page={{ movie.previous_page_number }}" style="background-color:#1aa3ff !important; color: white !important;"><span aria-hidden="true">&larr;</span> Previous</a>
    {% endif %}
    </li>
      <li class="previous" style="color: black !important;">
          Page {{ car.number }} of {{ car.paginator.num_pages }}.

    </li>
    <li class="next">{% if car.has_next %}
            <a href="?page={{ movie.next_page_number }}" style="background-color:#1aa3ff !important; color: white !important;">
        Next <span aria-hidden="true">&rarr;</span></a>{% endif %}</li>
  </ul>
</nav>
        <hr>

</div>

</div>



</div> <!--end container-->
{% endblock %}

templates/available_movie.html
{% extends 'base.html' %}
{% block title %}  Movie List {% endblock %}

{% block delete_confirm %}
        <script type="text/javascript">
        // <!--
            function getConfirmation(){
               return confirm("Do you want to Delete ?");
            }
         //-->
      </script>
    {% endblock %}

{% block body %}
<div class='container'>
    <div class ='col-sm-6 col-sm-offset-3'>
    <from>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From</span>
            <input type="date" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
        </div>
         <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">To</span>
              <input type="date" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
         </div>

       <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Show Movie</button>

    </from>
    </div>



</div> <!--end container-->
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Car Rental System {% endblock %}</title>

    <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<body>

<nav class="navbar navbar-custom navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="glyphicon glyphicon-align-justify"></span>

      </button>
      <div class="navbar-brand"><span class="glyphicon glyphicon-fire"></span> Car Rental</div>


    </div>

      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
         <li>
             {% block search %}
            <!-- search box-->

      <form method="GET" class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Car Search" value="{{request.GET.q}}" name="q">
        </div>
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Search</button>
      </form>
    {% endblock %}

{% block nav %}
        <li><a href="{% url 'newcar' %}"><span class="glyphicon glyphicon-align-justify"></span> Newly Added Car</a></li>
        <li><a href="{% url 'popularcar' %}"><span class="glyphicon glyphicon-star"></span> Popular car</a></li>
        <li><a href="{% url 'contact' %}"><span class="glyphicon glyphicon-envelope"></span> Contact</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-share"></span> Logout</a></li>
{% endblock %}
      </ul>
    </div>


  </div>
</nav>


{% block body %}
<div class="container">

</div>
{% endblock %}
</body>
</html>

templates/car_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create Car {% endblock %}

{% block search %}
{% endblock %}
{% block nav %}

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'adminIndex' %}"><span class="glyphicon glyphicon-home"></span> Car List</a></li>
        <li><a href="{% url 'order_list' %}"><span class="glyphicon glyphicon-tags"></span> Order List</a></li>
        <li><a href="{% url 'message' %}"><span class="glyphicon glyphicon-envelope"></span> Message</a></li>
         <li><a href="{% url 'car_create' %}"><span class="glyphicon glyphicon-plus"></span> Add Car</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-share"></span> Logout</a></li>
      </ul>
    </div>

{% endblock %}
{% block body %}
<div class ='col-sm-6 col-sm-offset-3'>
    <div class="panel panel-primary">
<div class="list-group-item active">
    <strong><span class="glyphicon glyphicon-film"></span> Car Create</strong>
  </div><br>
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
      {{form|crispy}}

    <input type="submit" class='btn btn-primary' value="Create post">
</form>
        </div>
</div>
{% endblock %}

templates/car_detail.html
{% extends 'base.html' %}
{% block title %} Detail of {{detail.car_name}} {% endblock %}

{% block body %}

{% block search %}
{% endblock %}



<div class ='col-sm-6 col-sm-offset-3'>
  <div class="list-group-item active">
    <strong><span class="glyphicon glyphicon-film"></span> Car Detail</strong>
  </div>
  {% if detail.image %}
  <img src='{{ detail.image.url }}' class="img-responsive" alt="detail of car {{ detail.car_name }}" />
  {% endif %}
  <a href="" class="list-group-item"><strong>Car Name: </strong>{{detail.car_name}}</a>
  <a href="" class="list-group-item"><strong>Company Name   : </strong>{{detail.company_name}}</a>
  <a href="" class="list-group-item"><strong>Num Of Seat   : </strong>{{detail.num_of_seats}}</a>
  <a href="" class="list-group-item"><strong>Cost Per Day   : </strong>{{detail.cost_par_day}}</a>
  <a href="" class="list-group-item"><strong>Like   : </strong>{{detail.like}}</a>
  <a href="" class="list-group-item"><strong>Other Info   : </strong>{{detail.content}}</a><br>
  <div class="pull-right">
    <a href="{% url 'newcar' %}"><button type="button" class="btn btn-info"><span class="glyphicon glyphicon-list"></span> Newly Added Car</button></a>
    <a href="{% url 'order_create' %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Book</button></a>
    
<hr>
  </div>

</div>

{% endblock %}

templates/car_list.html
{% extends 'base.html' %}
{% block title %}  Car List {% endblock %}

{% block delete_confirm %}
       
    {% endblock %}
{% block nav %}
<ul>
        <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
        <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-share"></span> Login</a></li>
</ul>
{% endblock %}
{% block body %}
<div class="container" style="margin-top: 15px;">
<div class="row">
        {% for ob in car %}

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            {% if ob.image %}
                <img src='{{ ob.image.url }}' class="img-responsive" alt="Car registration: {{ ob.car_name }}"/>
            {% endif %}
          <div class="caption">
            <strong>{{ ob.car_name }}</strong>
            <p> Company Name: {{ ob.company_name }}<br>
                Num Of Seats: {{ ob.num_of_seats }}<br>
                Cost Per Day: {{ ob.cost_par_day }} Taka<br>
            </p>
              {% if user.is_staff %}
              <div class="pull-right">
            <p>
              <button onclick="window.location.href='{% url 'car_detail' ob.id %}'" class="btn btn-primary">
                Detail
              </button>
              <button onclick="window.location.href='{% url 'order_create' %}'" class="btn btn-danger">
                Book
              </button>
            </p>
              </div>
              {% endif %}
          </div>
        </div>
      </div>

        {% endfor %}
</div>

    <nav>
  <ul class="pager">
    <li class="previous">{% if car.has_previous %}
            <a href="?page={{ car.previous_page_number }}" style="background-color:#1aa3ff !important; color: white !important;"><span aria-hidden="true">&larr;</span> Previous</a>
    {% endif %}
    </li>
      <li class="previous" style="color: black !important;">
          Page {{ car.number }} of {{ car.paginator.num_pages }}.

    </li>
    <li class="next">{% if car.has_next %}
            <a href="?page={{ car.next_page_number }}" style="background-color:#1aa3ff !important; color: white !important;">
        Next <span aria-hidden="true">&rarr;</span></a>{% endif %}</li>
  </ul>
</nav>
        <hr>
</div>



{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Contact Us {% endblock %}

{% block search %}

{% endblock %}
{% block nav %}
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'newcar' %}"><span class="glyphicon glyphicon-align-justify"></span> New Added Car</a></li>
        <li><a href="{% url 'popularcar' %}"><span class="glyphicon glyphicon-star"></span> Popular Car</a></li>
        <li><a href="{% url 'contact' %}"><span class="glyphicon glyphicon-envelope"></span> Contact</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
      </ul>
    </div>
{% endblock %}
{% block body %}
<div class ='col-sm-5 col-sm-offset-3'>
    <h1>{{ title }}</h1><hr>

    <form method="POST" action="">{% csrf_token %}
      {{form|crispy}}
        <div class="pull-right">
            <input type="submit" class="btn btn-primary" value="Send"/>
        </div>

</form>
</div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{title}} {% endblock %}

{% block search %}

{% endblock %}
{% block nav %}
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'car_list' %}"><span class="glyphicon glyphicon-list"></span> Car List</a></li>
        <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-share"></span> Login</a></li>
        <li><a href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
      </ul>
    </div>
{% endblock %}
{% block body %}
<div class ='col-sm-5 col-sm-offset-3'>
    <h1>{{ title }}</h1><hr>

    <form method="POST" action="">{% csrf_token %}
      {{form|crispy}}
        <div class="pull-right">
            <input type="submit" class="btn btn-primary" value="{{ title }}"/>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-link">Esqueceu a senha?</a>
        </div>

</form>
</div>
{% endblock %}

templates/new_car.html
{% extends 'base.html' %}
{% block title %}  Newly Added car {% endblock %}


{% block nav %}
    <ul>
        <li><a href="{% url 'newcar' %}"><span class="glyphicon glyphicon-align-justify"></span> Newly Added Car</a></li>
        <li><a href="{% url 'popularcar' %}"><span class="glyphicon glyphicon-star"></span> Popular car</a></li>
        <li><a href="{% url 'contact' %}"><span class="glyphicon glyphicon-envelope"></span> Contact</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-share"></span> Logout {{request.user.username}}</a></li>
    </ul>
{% endblock %}
{% block body %}
<div class="container" style="margin-top: 15px;">
<div class="row">
        {% for ob in car %}

      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            {% if ob.image %}
                <img src='{{ ob.image.url }}' class="img-responsive" alt="New {{ ob.car_name }}"/>
            {% endif %}
          <div class="caption">
            <strong>{{ ob.car_name }}</strong>
            <p> Company Name: {{ ob.company_name }}<br>
                Num Of Seats: {{ ob.num_of_seats }}<br>
                Cost Per Day: {{ ob.cost_par_day }} Taka<br>
            </p>
              <div class="pull-right">
            <p>
                <button onclick="window.location.href='{% url 'like' ob.id %}'" class="btn btn-success">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                </button>
                <button onclick="window.location.href='{% url 'car_detail' ob.id %}'" class="btn btn-primary">
                    Detail
                </button>
                <button onclick="window.location.href='{% url 'order_create' %}'" class="btn btn-danger">
                    Book
                </button>
            </p>
              </div>
          </div>
        </div>
      </div>


        {% endfor %}
</div>

    <nav>
  <ul class="pager">
    <li class="previous">{% if car.has_previous %}
            <a href="?page={{ car.previous_page_number }}" style="background-color:#1aa3ff !important; color: white !important;"><span aria-hidden="true">&larr;</span> Previous</a>
    {% endif %}
    </li>
      <li class="previous" style="color: black !important;">
          Page {{ car.number }} of {{ car.paginator.num_pages }}.

    </li>
    <li class="next">{% if movie.has_next %}
            <a href="?page={{ car.next_page_number }}" style="background-color:#1aa3ff !important; color: white !important;">
        Next <span aria-hidden="true">&rarr;</span></a>{% endif %}</li>
  </ul>
</nav>
        <hr>
</div>



{% endblock %}

templates/order_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create Order {% endblock %}

{% block search_box %}

{% endblock %}
{% block nav %}
  <ul>
        <li><a href="{% url 'newcar' %}"><span class="glyphicon glyphicon-align-justify"></span> Newly Added Car</a></li>
        <li><a href="{% url 'popularcar' %}"><span class="glyphicon glyphicon-star"></span> Popular car</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-share"></span> Logout</a></li>
  </ul>
{% endblock %}
{% block body %}

<div class ='col-sm-6 col-sm-offset-3'>
<div class="panel panel-primary">
<p class="list-group-item active">
    <strong><span class="glyphicon glyphicon-tag"></span> Book Your Car</strong>
  </p><br>
<form method="POST" action="" >{% csrf_token %}

      {{form|crispy}}
</div>
    </div>
  <div class="form-group row">
    <div class="col-sm-offset-3 col-sm-10">
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Book</button>
    </div>
  </div>
</form>


{% endblock %}

templates/order_detail.html
{% extends 'base.html' %}
{% block title %} Order Detail {% endblock %}

{% block body %}


<div class ='col-sm-6 col-sm-offset-3'>
  <strong><p style="color: red">Your booking was successfully.We will contact you soon regarding your booking.Your booking details are as bellow
  </p></strong>
  <p class="list-group-item active">
    <strong><span class="glyphicon glyphicon-tag"></span> Booking Detail</strong>
  </p>
   <a href="" class="list-group-item"><strong>Car name: </strong>{{detail.car_name}}</a>
  <a href="" class="list-group-item"><strong>Employee name: </strong>{{detail.employee_name}}</a>
  <a href="" class="list-group-item"><strong>Phone No: </strong>{{detail.cell_no}}</a>
  <a href="" class="list-group-item"><strong>Address: </strong>{{detail.address}}</a>
  <a href="" class="list-group-item"><strong>From: </strong>{{detail.date}}</a>
  <a href="" class="list-group-item"><strong>To: </strong>{{detail.to}}</a>
  <a href="" class="list-group-item"><strong>Order Id: </strong>{{detail.id}}</a><br>
  <div class="pull-right">
    <a href="{% url 'order_edit' detail.id %}"><button type="button" class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span> Edit Booking</button></a>
    <a href="{% url 'order_delete' detail.id %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-pencil"></span> Cancel Booking</button></a>
    <a href=""><button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span> Print</button></a>

  </div>
</div>

{% endblock %}

templates/order_list.html
{% extends 'base.html' %}
{% block title %} List Order {% endblock %}
{% block search %}
{% endblock %}
{% block nav %}

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'adminIndex' %}"><span class="glyphicon glyphicon-home"></span> Car List</a></li>
        <li><a href="{% url 'order_list' %}"><span class="glyphicon glyphicon-tags"></span> Order List</a></li>
        <li><a href="{% url 'message' %}"><span class="glyphicon glyphicon-envelope"></span> Message</a></li>
        <li><a href="{% url 'car_create' %}"><span class="glyphicon glyphicon-plus"></span> Add Car</a></li>
        <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-share"></span> Logout</a></li>
      </ul>
    </div>

{% endblock %}
{% block body %}
<div class='container table-responsive'>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong><span class="glyphicon glyphicon-list"></span> All Order List</strong> </div>
    <div class="panel-body">
    <strong class="navbar-form navbar-left" style="color: #5f5f5f;"><span class="glyphicon glyphicon-cog"></span> 25 Order Display Per Page </strong>
    {% block search_box %}
      <form method="GET" class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Order Search" value="{{request.GET.q}}" name="q">
        </div>
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Search</button>
      </form>
      {% endblock %}

  <!-- Table -->
  <table class="table table-bordered table-striped table-hover">
   <tr>
   <th scope="col">Order ID</th>
    <th scope="col">Employee Name</th>
    <th scope="col">Phone No</th>
    <th scope="col">Car Name</th>
    <th scope="col">From</th>
    <th scope="col">To</th>
    <th scope="col">Action</th>
  </tr>

      {% for ob in order %}
    <tr>
    <td>{{ob.id}} ORD</td>
    <td>{{ob.employee_name}}</td>
    <td>{{ob.cell_no}}</td>
    <td>{{ob.car_name}}</td>
    <td>{{ob.date}}</td>
    <td>{{ob.to}}</td>
    <td>

         <a href="{% url 'order_detail' ob.id %}"><button type="button" class="btn btn-info"><span class="glyphicon glyphicon-eye-open"></span></button></a>
         <a href="{% url 'order_delete' ob.id %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></button></a>

    </td>
</tr>
    {% endfor %}

  </table>



<nav>
  <ul class="pager">
    <li class="previous">{% if order.has_previous %}
            <a href="?page={{ order.previous_page_number }}" style="background-color:#1aa3ff !important; color: white !important;"><span aria-hidden="true">&larr;</span> Previous</a>
    {% endif %}
    </li>
      <li class="previous">
         <strong> Page {{ order.number }} of {{ order.paginator.num_pages }}.</strong>

    </li>
    <li class="next">{% if order.has_next %}
            <a href="?page={{ order.next_page_number }}" style="background-color:#1aa3ff !important; color: white !important;">
        Next <span aria-hidden="true">&rarr;</span></a>{% endif %}</li>
  </ul>
</nav>
    <hr>

    </div>
    </div>
{% endblock %}

templates/popular_car.html
This is popular page